version: "3.9"
services:
  nginx:
    build:
      context: ..
      dockerfile: Dockerfiles/document_server.Dockerfile
    image: sphinx-server
    container_name: sphinx-server
    volumes:
      - ../docs:/docs
    restart: always
    ports:
      - 80:80