version: "3.3"
services:
  nginx:
    build:
      context: ..
      dockerfile: Dockerfiles/document_server.Dockerfile
    image: sphinx-server
    container_name: sphinx-server
    volumes:
      - ../docs:/docs
    restart: always
    ports:
      - 80:80

  pypiserver:
    image: pypiserver/pypiserver:latest
    container_name: pypiserver
    volumes:
      - ~/packages:/data/packages
    restart: always
    ports:
      - 8008:8080
    command: -P /data/packages/htpasswd.txt --overwrite
      