name: Deploy
on: push
  # release:
  #   types: [published]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Check version
      run: |
        pyenv local onebone
        sh tools/check_version.sh ${GITHUB_REF#refs/*/}
    - name: Build & Deploy
      run: |
        poetry build
        poetry publish -r onebone
