name: Document deploy
on:
  push:
    branches:
      - main
jobs:
  document-deploy:
    runs-on: [self-hosted, linux, x64, deploy]
    steps:
    - uses: actions/checkout@v1
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Pull & Document build
      working-directory: /home/kyunghwan/opt/oplib
      run: |
        git pull origin main
        pyenv local oplib
        make sphinx-build
