name: Document deploy
on: [push]
jobs:
  document-deploy:
    runs-on: [self-hosted, linux, x64, deploy]
    steps:
    - name: Pull & Document build
      uses: actions/checkout@v1
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      working-directory: /home/kyunghwan/opt/oplib
      run: |
        git pull origin main
        pyenv local oplib
        make sphinx-build
