name: Document deploy
on:
  push:
    branches:
      - main
jobs:
  document-deploy:
    runs-on: [self-hosted, linux, x64, deploy]
    steps:
    - uses: actions/checkout@v1
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Pull & Document build
      working-directory: /home/kyunghwan/opt/onebone
      run: |
        rm -rf docs/build/html
        find docs/source -type f -name "*.rst" -not -name "index.rst" -delete
        git pull origin main
        pyenv local onebone
        make sphinx-build
